# Generated by Django 2.0 on 2017-12-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabioapp', '0002_auto_20171218_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfile',
            name='download_file',
            field=models.FileField(upload_to='media/downloadfile/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='media/uploadfile/'),
        ),
    ]
