# Generated by Django 2.0 on 2017-12-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabioapp', '0003_auto_20171220_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JSON_file', models.FileField(upload_to='media/jsonfile')),
            ],
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='download_file',
            field=models.FileField(upload_to='media/downloadfile'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='media//uploadfile'),
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='download_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabioapp.DownloadFile'),
        ),
    ]
