# Generated by Django 2.0 on 2017-12-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabioapp', '0004_auto_20171229_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='media/uploadfile'),
        ),
    ]
