# Generated by Django 2.0 on 2018-01-04 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabioapp', '0005_auto_20171229_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_json', models.FileField(upload_to='media//inputjson')),
            ],
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='download_file',
            field=models.FileField(upload_to='media//downloadfile'),
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='JSON_file',
            field=models.FileField(upload_to='media//jsonfile'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='media//uploadfile'),
        ),
        migrations.AddField(
            model_name='inputjson',
            name='upload_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabioapp.UploadFile'),
        ),
    ]
