# Generated by Django 2.0 on 2018-01-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabioapp', '0006_auto_20180104_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JSON_file', models.FileField(upload_to='media//outputjson')),
                ('download_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabioapp.DownloadFile')),
            ],
        ),
        migrations.RemoveField(
            model_name='jsonfile',
            name='download_file',
        ),
        migrations.DeleteModel(
            name='JSONFile',
        ),
    ]
